name: automated_testing_framework_example
description: Example project for the Automated Testing Framework that provides a reusable example across add ons.
homepage: https://github.com/peiffer-innovations/automated_testing_framework_example

version: 2.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  automated_testing_framework: ^3.0.6+3
  flutter:
    sdk: flutter
  flutter_slidable: ^0.6.0
  form_validation: ^2.0.0
  intl: ^0.17.0
  meta: ^1.3.0
  provider: ^5.0.0
  static_translations: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  automated_testing_framework:
    path: ../automated_testing_framework

flutter:
  uses-material-design: true
  assets:
    - assets/all_tests.json
    - assets/tests/
