name: automated_testing_framework_example
description: Example project for the Automated Testing Framework that provides a reusable example across add ons.
homepage: https://github.com/peiffer-innovations/automated_testing_framework_example

version: 1.0.12+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  automated_testing_framework: ^1.3.3+2
  flutter:
    sdk: flutter
  form_validation: ^1.0.2+1
  intl: ^0.16.1
  meta: ^1.2.4
  provider: ^4.3.2+4
  static_translations: ^1.0.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter

# dependency_overrides:
#   automated_testing_framework:
#     path: ../automated_testing_framework

flutter:
  uses-material-design: true
  assets:
    - assets/all_tests.json
    - assets/tests/
