name: 'automated_testing_framework_example'
description: 'Example project for the Automated Testing Framework that provides a reusable example across add ons.'
homepage: 'https://github.com/peiffer-innovations/automated_testing_framework_example'
version: '2.3.2'

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  automated_testing_framework: '^5.0.0'
  flutter:
    sdk: 'flutter'
  flutter_slidable: '>=1.3.1 <3.0.0'
  form_validation: '^2.1.0+9'
  intl: '^0.18.0'
  logging: '^1.0.2'
  meta: '^1.8.0'
  provider: '^6.0.3'
  static_translations: '^2.1.1+6'

dev_dependencies:
  flutter_test:
    sdk: 'flutter'

flutter:
  uses-material-design: true
  assets:
    - 'assets/all_tests.json'
    - 'assets/tests/'

ignore_updates:
  - 'archive'
  - 'async'
  - 'boolean_selector'
  - 'characters'
  - 'charcode'
  - 'collection'
  - 'clock'
  - 'crypto'
  - 'fake_async'
  - 'file'
  - 'matcher'
  - 'material_color_utilities'
  - 'meta'
  - 'path'
  - 'source_span'
  - 'stack_trace'
  - 'stream_channel'
  - 'string_scanner'
  - 'sync_http'
  - 'term_glyph'
  - 'test_api'
  - 'typed_data'
  - 'vector_math'
  - 'webdriver'
