name: automated_testing_framework_example
description: Example project for the Automated Testing Framework that provides a reusable example across add ons.
homepage: https://github.com/peiffer-innovations/automated_testing_framework_example

version: 2.2.1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  automated_testing_framework: ^3.2.2
  flutter:
    sdk: flutter
  flutter_slidable: ^0.6.0
  form_validation: ^2.1.0+1
  intl: ^0.17.0
  logging: ^1.0.2
  meta: ^1.7.0
  provider: ^6.0.0
  static_translations: ^2.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

# dependency_overrides:
#   automated_testing_framework:
#     path: ../automated_testing_framework

flutter:
  uses-material-design: true
  assets:
    - assets/all_tests.json
    - assets/tests/
